### ISSUE TITLE
El Super Usuario no se puede cambiar a otro rol y tampoco se puede deshabilitar

### ISSUE THREAD

**Issue by danielmorales** [seba1165/SSMS-PSA_y_Epicrisis#14]

**Comment by seba1165** [comment]
Hay caso de prueba para esto ? Para hacer lo mismo y ver el bug mas especifico

**Comment by danielmorales** [comment]
Para este caso no. Por casualidad probé que un Super Usuario podía cambiar a otro ROL y también podía deshabilitar a otro Super Usuario.
