### ISSUE TITLE
Editar CLAP de menor de 15 años

### ISSUE THREAD

**Issue by danielmorales** [seba1165/SSMS-PSA_y_Epicrisis#26]
Al tener un paciente menor a 15 años, con una ficha Clap asociada (con riesgo de alcohol), si edito la edad del paciente y luego edito la ficha Clap en la parte de consumo de alcohol, arroja el siguiente mensaje

![captura](https://cloud.githubusercontent.com/assets/9301185/15624323/6d2c266a-245b-11e6-87af-f4b4e55216e8.JPG)

**Comment by seba1165** [comment]
Reparado en commit de reparacion de bug #22
